name: C_C++_CI

on:
  pull_request:
    branches:
      - master


jobs:
  unit-test:
    uses: NWChemEx-Project/.github/.github/workflows/c-cpp_tmpl.yml@master
    with: 
      dependencies: 'gcc gcovr cmake'

