name: C_C++_CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmake_version: [3.16.3]
        gcc_version: [9]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with: 
         python-version: '3.x'
    - name: Get dependencies
      env:
        cmake_version: ${{ matrix.cmake_version }}
        gcc_version: ${{ matrix.gcc_version }}
      run: sudo .github/workflows/scripts/get_dependencies.sh gcc cmake
    - name: Configure
      run:  cmake-3.16.3-Linux-x86_64/bin/cmake -H. -Bbuild -DBUILD_TESTING=TRUE -DCATCH_ENABLE_COVERAGE=ON -DCMAKE_CXX_FLAGS="--coverage" -DCMAKE_C_FLAGS="--coverage" -DCMAKE_EXE_LINKER_FLAGS="-fprofile-arcs"
    - name: Build and test
      run:  cmake-3.16.3-Linux-x86_64/bin/ctest --build-and-test build build --build-nocmake --build-generator "Unix Makefiles" --test-command make test
    - name: Get coverage
      run: |
           cd ..
           gcovr --root Utilities --filter Utilities --exclude Utilities/tests --xml Utilities/coverage.xml
           ls -al Utilities
    - uses: codecov/codecov-action@v1
      with:
         token: ${{ secrets.CODECOV_TOKEN }}
         file: ./coverage.xml
