name: Lint Master
on:
  pull_request:
    branches:
      - master

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - name: obtain-source
        uses: actions/checkout@v2
#      - name: new-branch
#        env:
#          hash_value: ${{ github.sha }}
#        run: git checkout -b ${hash_value}-#pr
      - name: get-lint-settings
        run:  wget https://raw.githubusercontent.com/NWChemEx-Project/DeveloperTools/master/ci/lint/clang-format.in -O .clang-format
      - name: get-clang-format
        run: |
              sudo apt update
              sudo apt-get install -f clang-format-9
      - name: run-clang-format
        run: |
              find utilities -name '*.hpp' -or -name '*.cpp' | xargs clang-format-9 -style=file -i -fallback-style=none
#      - name: commit-changes
#        id: changes
#        run: |
#              diff_value=`git diff`
#              if [ ! -z "$diff_value" ]
#              then
#                  git config --local user.email "action@github.com"
#                  git config --local user.name "GitHub Action"
#                  git commit -m "linted source" -a
#              fi
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}


