name: Test Documentation
on:
  pull_request:
    branches:
      - master


jobs:
  Build-Documentation:
    uses: NWChemEx-Project/.github/.github/workflows/test_docs_tmpl.yml@master
    with:
      target: utilities_cxx_api
      dependencies: cmake doxygen sphinx

