name: Test Documentation
on:
  pull_request:
    branches:
      - master

jobs:
  Build-Documentation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmake_version: [3.16.3]
    steps:
      - name: Obtain Source
        uses: actions/checkout@v2
      - name: Get dependencies
        env:
          cmake_version: ${{ matrix.cmake_version }}
        run: sudo scripts/get_dependencies.sh cmake doxygen sphinx
      - name: Build Doxygen Documentation
        run: |
              cmake-${cmake_version}-${arch}/bin/cmake -H. -Bbuild
              cmake-${cmake_version}-${arch}/bin/cmake --build build --target cxx_api
      - name: Move Doxygen Documentation to Docs
        run: |
              mkdir docs/build
              mkdir docs/build/html
              mv build/html docs/build/html/cxx_api
      - name: Build Sphinx Documentation
        run: |
              source venv/bin/activate
              cd docs
              make html

